version: '3.9'
services:
  admin:
    container_name: admin
    restart: always
    #    env_file:
    #      - ./docker/development/.env
    build:
      context: ./
      dockerfile: ./docker/development/Dockerfile
    #      target: dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '${DOCKER_APP_PORT:-80}:80'
    environment:
      NODE_ENV: 'development'
    # network_mode: host
    networks:
      - emm_saas
networks:
  emm_saas:
    driver: bridge

volumes:
  emm_saas-admin:
    driver: local
