export const permissions = [
  {
    id: 1,
    name: "find users",
    name_ar: "عرض المستخدمين",
    slug: "users:find",
    category: "users",
    action: "find",
  },
  {
    id: 2,
    name: "findOne users",
    name_ar: "عرض مستخدم واحد",
    slug: "users:findOne",
    category: "users",
    action: "findOne",
  },
  {
    id: 3,
    name: "create users",
    name_ar: "إنشاء مستخدم",
    slug: "users:create",
    category: "users",
    action: "create",
  },
  {
    id: 4,
    name: "update users",
    name_ar: "تحديث مستخدم",
    slug: "users:update",
    category: "users",
    action: "update",
  },
  {
    id: 5,
    name: "delete users",
    name_ar: "حذف مستخدم",
    slug: "users:delete",
    category: "users",
    action: "delete",
  },
  {
    id: 6,
    name: "find roles",
    name_ar: "عرض جميع الأدوار",
    slug: "roles:find",
    category: "roles",
    action: "find",
  },
  {
    id: 7,
    name: "findOne roles",
    name_ar: "عرض دور واحد",
    slug: "roles:findOne",
    category: "roles",
    action: "findOne",
  },
  {
    id: 8,
    name: "create roles",
    name_ar: "إنشاء دور",
    slug: "roles:create",
    category: "roles",
    action: "create",
  },
  {
    id: 9,
    name: "update roles",
    name_ar: "تحديث الأدوار",
    slug: "roles:update",
    category: "roles",
    action: "update",
  },
  {
    id: 10,
    name: "delete roles",
    name_ar: "حذف الأدوار",
    slug: "roles:delete",
    category: "roles",
    action: "delete",
  },
  {
    id: 11,
    name: "find permissions",
    name_ar: "عرض الأذونات",
    slug: "permissions:find",
    category: "permissions",
    action: "find",
  },
  {
    id: 12,
    name: "findOne permissions",
    name_ar: "عرض إذن واحد",
    slug: "permissions:findOne",
    category: "permissions",
    action: "findOne",
  },
  {
    id: 13,
    name: "create permissions",
    name_ar: "إنشاء إذن",
    slug: "permissions:create",
    category: "permissions",
    action: "create",
  },
  {
    id: 14,
    name: "update permissions",
    name_ar: "تحديث الأذونات",
    slug: "permissions:update",
    category: "permissions",
    action: "update",
  },
  {
    id: 15,
    name: "delete permissions",
    name_ar: "حذف الأذونات",
    slug: "permissions:delete",
    category: "permissions",
    action: "delete",
  },
  {
    id: 16,
    name: "find product_categories",
    name_ar: "عرض فئات المنتجات",
    slug: "product_categories:find",
    category: "product_categories",
    action: "find",
  },
  {
    id: 17,
    name: "findOne product_categories",
    name_ar: "عرض فئة منتج واحدة",
    slug: "product_categories:findOne",
    category: "product_categories",
    action: "findOne",
  },
  {
    id: 18,
    name: "create product_categories",
    name_ar: "إنشاء فئة المنتج",
    slug: "product_categories:create",
    category: "product_categories",
    action: "create",
  },
  {
    id: 19,
    name: "update product_categories",
    name_ar: "تحديث فئة المنتج",
    slug: "product_categories:update",
    category: "product_categories",
    action: "update",
  },
  {
    id: 20,
    name: "delete product_categories",
    name_ar: "حذف فئة المنتج",
    slug: "product_categories:delete",
    category: "product_categories",
    action: "delete",
  },
  {
    id: 21,
    name: "find products",
    name_ar: "عرض المنتجات",
    slug: "products:find",
    category: "products",
    action: "find",
  },
  {
    id: 22,
    name: "findOne products",
    name_ar: "عرض منتج واحد",
    slug: "products:findOne",
    category: "products",
    action: "findOne",
  },
  {
    id: 23,
    name: "create products",
    name_ar: "إنشاء منتج",
    slug: "products:create",
    category: "products",
    action: "create",
  },
  {
    id: 24,
    name: "update products",
    name_ar: "تحديث المنتجات",
    slug: "products:update",
    category: "products",
    action: "update",
  },
  {
    id: 25,
    name: "delete products",
    name_ar: "حذف المنتجات",
    slug: "products:delete",
    category: "products",
    action: "delete",
  },
  {
    id: 26,
    name: "find countries",
    name_ar: "البحث عن الدول",
    slug: "countries:find",
    category: "countries",
    action: "find",
  },
  {
    id: 27,
    name: "findOne countries",
    name_ar: "البحث عن بلد واحد",
    slug: "countries:findOne",
    category: "countries",
    action: "findOne",
  },
  {
    id: 28,
    name: "create countries",
    name_ar: "إنشاء بلد",
    slug: "countries:create",
    category: "countries",
    action: "create",
  },
  {
    id: 29,
    name: "update countries",
    name_ar: "تحديث الدول",
    slug: "countries:update",
    category: "countries",
    action: "update",
  },
  {
    id: 30,
    name: "delete countries",
    name_ar: "حذف الدول",
    slug: "countries:delete",
    category: "countries",
    action: "delete",
  },
  {
    id: 31,
    name: "find cities",
    name_ar: "عرض المدن",
    slug: "cities:find",
    category: "cities",
    action: "find",
  },
  {
    id: 32,
    name: "findOne cities",
    name_ar: "عرض مدينة واحدة",
    slug: "cities:findOne",
    category: "cities",
    action: "findOne",
  },
  {
    id: 33,
    name: "create cities",
    name_ar: "إنشاء مدينة",
    slug: "cities:create",
    category: "cities",
    action: "create",
  },
  {
    id: 34,
    name: "update cities",
    slug: "cities:update",
    category: "cities",
    action: "update",
  },
  {
    id: 35,
    name: "delete cities",
    name_ar: "حذف المدن",
    slug: "cities:delete",
    category: "cities",
    action: "delete",
  },
  {
    id: 36,
    name: "find orders",
    name_ar: "عرض الطلبات",
    slug: "orders:find",
    category: "orders",
    action: "find",
  },
  {
    id: 37,
    name: "findOne orders",
    name_ar: "عرض طلب واحد",
    slug: "orders:findOne",
    category: "orders",
    action: "findOne",
  },
  {
    id: 38,
    name: "create orders",
    name_ar: "إنشاء طلب",
    slug: "orders:create",
    category: "orders",
    action: "create",
  },
  {
    id: 39,
    name: "update orders",
    name_ar: "تحديث الطلبات",
    slug: "orders:update",
    category: "orders",
    action: "update",
  },
  {
    id: 40,
    name: "delete orders",
    name_ar: "حذف الطلبات",
    slug: "orders:delete",
    category: "orders",
    action: "delete",
  },
  {
    id: 41,
    name: "find customers",
    name_ar: "البحث عن العملاء",
    slug: "customers:find",
    category: "customers",
    action: "find",
  },
  {
    id: 42,
    name: "findOne customers",
    name_ar: "البحث عن عميل",
    slug: "customers:findOne",
    category: "customers",
    action: "findOne",
  },
  {
    id: 43,
    name: "create customers",
    name_ar: "إنشاء عميل",
    slug: "customers:create",
    category: "customers",
    action: "create",
  },
  {
    id: 44,
    name: "update customers",
    name_ar: "تحديث العملاء",
    slug: "customers:update",
    category: "customers",
    action: "update",
  },
  {
    id: 45,
    name: "delete customers",
    name_ar: "حذف العملاء",
    slug: "customers:delete",
    category: "customers",
    action: "delete",
  },
  {
    id: 46,
    name: "find clients",
    name_ar: "عرض جميع العملاء",
    slug: "clients:find",
    category: "clients",
    action: "find",
  },
  {
    id: 47,
    name: "findOne clients",
    name_ar: "عرض عميل واحد",
    slug: "clients:findOne",
    category: "clients",
    action: "findOne",
  },
  {
    id: 48,
    name: "create clients",
    name_ar: "إنشاء عميل",
    slug: "clients:create",
    category: "clients",
    action: "create",
  },
  {
    id: 49,
    name: "update clients",
    name_ar: "تحديث العملاء",
    slug: "clients:update",
    category: "clients",
    action: "update",
  },
  {
    id: 50,
    name: "delete clients",
    name_ar: "حذف العملاء",
    slug: "clients:delete",
    category: "clients",
    action: "delete",
  },
  {
    id: 51,
    name: "find wallet",
    name_ar: "البحث عن المحفظة",
    slug: "wallet:find",
    category: "wallet",
    action: "find",
  },
  {
    id: 52,
    name: "findOne wallet",
    name_ar: "البحث عن المحفظة",
    slug: "wallet:findOne",
    category: "wallet",
    action: "findOne",
  },
  {
    id: 53,
    name: "create wallet",
    name_ar: "إنشاء محفظة",
    slug: "wallet:create",
    category: "wallet",
    action: "create",
  },
  {
    id: 54,
    name: "update wallet",
    name_ar: "تحديث المحفظة",
    slug: "wallet:update",
    category: "wallet",
    action: "update",
  },
  {
    id: 55,
    name: "delete wallet",
    name_ar: "حذف المحفظة",
    slug: "wallet:delete",
    category: "wallet",
    action: "delete",
  },
  {
    id: 56,
    name: "find withdrawals",
    name_er: "عرض جميع عمليات السحب",
    slug: "withdrawals:find",
    category: "withdrawals",
    action: "find",
  },
  {
    id: 57,
    name: "findOne withdrawals",
    name_ar: "عرض عمليه السحب",
    slug: "withdrawals:findOne",
    category: "withdrawals",
    action: "findOne",
  },
  {
    id: 58,
    name: "update withdrawals",
    name_ar: "تحديث السحب",
    slug: "withdrawals:update",
    category: "withdrawals",
    action: "update",
  },
  {
    id: 59,
    name: "delete withdrawals",
    name_ar: "حذف السحب",
    slug: "withdrawals:delete",
    category: "withdrawals",
    action: "delete",
  },
  {
    id: 60,
    name: "find transactions",
    name_ar: "عرض جميع المعاملات",
    slug: "transactions:find",
    category: "transactions",
    action: "find",
  },
  {
    id: 61,
    name: "findOne transactions",
    name_ar: "عرض معامله واحده",
    slug: "transactions:findOne",
    category: "transactions",
    action: "findOne",
  },
  {
    id: 62,
    name: "create transactions",
    name_ar: "إنشاء معاملة",
    slug: "transactions:create",
    category: "transactions",
    action: "create",
  },
  {
    id: 63,
    name: "update transactions",
    name_ar: "تحديث المعاملات",
    slug: "transactions:update",
    category: "transactions",
    action: "update",
  },
  {
    id: 64,
    name: "delete transactions",
    name_ar: "حذف المعاملات",
    slug: "transactions:delete",
    category: "transactions",
    action: "delete",
  },
  {
    id: 65,
    name: "find dashboard statistics",
    name_ar:"عرض جميع الاحصائيات",
    slug: "dashboard-statistics:find",
    category: "dashboard",
    action: "find",
  },
  {
    id: 66,
    name: "find faq",
    name_ar: "عرض الاسئله الشائعه",
    slug: "faq:find",
    category: "faq",
    action: "find",
  },
  {
    id: 67,
    name: "findOne faq",
    name_ar: "عرض سؤال واحد",
    slug: "faq:findOne",
    category: "faq",
    action: "findOne",
  },
  {
    id: 68,
    name: "create faq",
    name_ar: "إنشاء الأسئلة الشائعة",
    slug: "faq:create",
    category: "faq",
    action: "create",
  },
  {
    id: 69,
    name: "update faq",
    name_ar: "تحديث الأسئلة الشائعة",
    slug: "faq:update",
    category: "faq",
    action: "update",
  },
  {
    id: 70,
    name: "delete faq",
    name_ar: "حذف الأسئلة الشائعة",
    slug: "faq:delete",
    category: "faq",
    action: "delete",
  },
  {
    id: 71,
    name: "find delivery notes",
    name_ar: "عرض ملاحظات الشحن",
    slug: "delivery_notes:find",
    category: "delivery_notes",
    action: "find",
  },
  {
    id: 72,
    name: "findOne delivery notes",
    name_ar: "عرض ملاحظه شحن واحده",
    slug: "delivery_notes:findOne",
    category: "delivery_notes",
    action: "findOne",
  },
  {
    id: 73,
    name: "create delivery notes",
    name_ar: "إنشاء ملاحظات التسليم",
    slug: "delivery_notes:create",
    category: "delivery_notes",
    action: "create",
  },
  {
    id: 74,
    name: "update delivery notes",
    name_ar: "تحديث ملاحظات التسليم",
    slug: "delivery_notes:update",
    category: "clients",
    action: "update",
  },
  {
    id: 75,
    name: "delete delivery notes",
    name_ar: "حذف ملاحظات التسليم",
    slug: "delivery_notes:delete",
    category: "delivery_notes",
    action: "delete",
  },
  {
    id: 76,
    name: "find testimonials",
    name_ar: "عرض جميع الاراء",
    slug: "testimonials:find",
    category: "testimonials",
    action: "find",
  },
  {
    id: 77,
    name: "findOne testimonials",
    name_ar: "عرض راي واحد",
    slug: "testimonials:findOne",
    category: "testimonials",
    action: "findOne",
  },
  {
    id: 78,
    name: "create testimonials",
    name_ar: "إنشاء الشهادات",
    slug: "testimonials:create",
    category: "testimonials",
    action: "create",
  },
  {
    id: 79,
    name: "update testimonials",
    name_ar: "تحديث الشهادات",
    slug: "testimonials:update",
    category: "testimonials",
    action: "update",
  },
  {
    id: 80,
    name: "delete testimonials",
    name_ar: "حذف الشهادات",
    slug: "testimonials:delete",
    category: "testimonials",
    action: "delete",
  },
];
