name: Deploy to server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Deploy to server
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: 138.68.133.151
        USER: root
      run: |
        echo "$PRIVATE_KEY" > private_key 
        chmod 600 private_key
         sshpass -p 2701_Hgfds  ssh  -o StrictHostKeyChecking=no  $USER@$HOST  " 
         cd /root/dashboard/WBNR_dashboard && git pull && docker stop wbnr-dashboard && docker rm wbnr-dashboard  &&
         docker build -t wbnr-dashboard .  && docker run -d -p 5050:80 --name=wbnr-dashboard wbnr-dashboard "
